// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: space-fighter/space-fighter-open-fire.proto

#include "space-fighter-open-fire.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace multiplayer {
class SpaceFighterOpenFireDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SpaceFighterOpenFire>
      _instance;
} _SpaceFighterOpenFire_default_instance_;
}  // namespace multiplayer
namespace protobuf_space_2dfighter_2fspace_2dfighter_2dopen_2dfire_2eproto {
static void InitDefaultsSpaceFighterOpenFire() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::multiplayer::_SpaceFighterOpenFire_default_instance_;
    new (ptr) ::multiplayer::SpaceFighterOpenFire();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::multiplayer::SpaceFighterOpenFire::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SpaceFighterOpenFire =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSpaceFighterOpenFire}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SpaceFighterOpenFire.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::SpaceFighterOpenFire, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::multiplayer::SpaceFighterOpenFire)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::multiplayer::_SpaceFighterOpenFire_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "space-fighter/space-fighter-open-fire.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n+space-fighter/space-fighter-open-fire."
      "proto\022\013multiplayer\"\026\n\024SpaceFighterOpenFi"
      "reb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 90);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "space-fighter/space-fighter-open-fire.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_space_2dfighter_2fspace_2dfighter_2dopen_2dfire_2eproto
namespace multiplayer {

// ===================================================================

void SpaceFighterOpenFire::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SpaceFighterOpenFire::SpaceFighterOpenFire()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_space_2dfighter_2fspace_2dfighter_2dopen_2dfire_2eproto::scc_info_SpaceFighterOpenFire.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:multiplayer.SpaceFighterOpenFire)
}
SpaceFighterOpenFire::SpaceFighterOpenFire(const SpaceFighterOpenFire& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:multiplayer.SpaceFighterOpenFire)
}

void SpaceFighterOpenFire::SharedCtor() {
}

SpaceFighterOpenFire::~SpaceFighterOpenFire() {
  // @@protoc_insertion_point(destructor:multiplayer.SpaceFighterOpenFire)
  SharedDtor();
}

void SpaceFighterOpenFire::SharedDtor() {
}

void SpaceFighterOpenFire::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SpaceFighterOpenFire::descriptor() {
  ::protobuf_space_2dfighter_2fspace_2dfighter_2dopen_2dfire_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_space_2dfighter_2fspace_2dfighter_2dopen_2dfire_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SpaceFighterOpenFire& SpaceFighterOpenFire::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_space_2dfighter_2fspace_2dfighter_2dopen_2dfire_2eproto::scc_info_SpaceFighterOpenFire.base);
  return *internal_default_instance();
}


void SpaceFighterOpenFire::Clear() {
// @@protoc_insertion_point(message_clear_start:multiplayer.SpaceFighterOpenFire)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool SpaceFighterOpenFire::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:multiplayer.SpaceFighterOpenFire)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:multiplayer.SpaceFighterOpenFire)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:multiplayer.SpaceFighterOpenFire)
  return false;
#undef DO_
}

void SpaceFighterOpenFire::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:multiplayer.SpaceFighterOpenFire)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:multiplayer.SpaceFighterOpenFire)
}

::google::protobuf::uint8* SpaceFighterOpenFire::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:multiplayer.SpaceFighterOpenFire)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:multiplayer.SpaceFighterOpenFire)
  return target;
}

size_t SpaceFighterOpenFire::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:multiplayer.SpaceFighterOpenFire)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SpaceFighterOpenFire::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:multiplayer.SpaceFighterOpenFire)
  GOOGLE_DCHECK_NE(&from, this);
  const SpaceFighterOpenFire* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SpaceFighterOpenFire>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:multiplayer.SpaceFighterOpenFire)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:multiplayer.SpaceFighterOpenFire)
    MergeFrom(*source);
  }
}

void SpaceFighterOpenFire::MergeFrom(const SpaceFighterOpenFire& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:multiplayer.SpaceFighterOpenFire)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void SpaceFighterOpenFire::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:multiplayer.SpaceFighterOpenFire)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpaceFighterOpenFire::CopyFrom(const SpaceFighterOpenFire& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:multiplayer.SpaceFighterOpenFire)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpaceFighterOpenFire::IsInitialized() const {
  return true;
}

void SpaceFighterOpenFire::Swap(SpaceFighterOpenFire* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SpaceFighterOpenFire::InternalSwap(SpaceFighterOpenFire* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SpaceFighterOpenFire::GetMetadata() const {
  protobuf_space_2dfighter_2fspace_2dfighter_2dopen_2dfire_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_space_2dfighter_2fspace_2dfighter_2dopen_2dfire_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace multiplayer
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::multiplayer::SpaceFighterOpenFire* Arena::CreateMaybeMessage< ::multiplayer::SpaceFighterOpenFire >(Arena* arena) {
  return Arena::CreateInternal< ::multiplayer::SpaceFighterOpenFire >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
