// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: space-fighter/space-fighter-input.proto

#ifndef PROTOBUF_INCLUDED_space_2dfighter_2fspace_2dfighter_2dinput_2eproto
#define PROTOBUF_INCLUDED_space_2dfighter_2fspace_2dfighter_2dinput_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_space_2dfighter_2fspace_2dfighter_2dinput_2eproto 

namespace protobuf_space_2dfighter_2fspace_2dfighter_2dinput_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_space_2dfighter_2fspace_2dfighter_2dinput_2eproto
namespace multiplayer {
class SpaceFighterInput;
class SpaceFighterInputDefaultTypeInternal;
extern SpaceFighterInputDefaultTypeInternal _SpaceFighterInput_default_instance_;
}  // namespace multiplayer
namespace google {
namespace protobuf {
template<> ::multiplayer::SpaceFighterInput* Arena::CreateMaybeMessage<::multiplayer::SpaceFighterInput>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace multiplayer {

// ===================================================================

class SpaceFighterInput : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:multiplayer.SpaceFighterInput) */ {
 public:
  SpaceFighterInput();
  virtual ~SpaceFighterInput();

  SpaceFighterInput(const SpaceFighterInput& from);

  inline SpaceFighterInput& operator=(const SpaceFighterInput& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SpaceFighterInput(SpaceFighterInput&& from) noexcept
    : SpaceFighterInput() {
    *this = ::std::move(from);
  }

  inline SpaceFighterInput& operator=(SpaceFighterInput&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SpaceFighterInput& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SpaceFighterInput* internal_default_instance() {
    return reinterpret_cast<const SpaceFighterInput*>(
               &_SpaceFighterInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SpaceFighterInput* other);
  friend void swap(SpaceFighterInput& a, SpaceFighterInput& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SpaceFighterInput* New() const final {
    return CreateMaybeMessage<SpaceFighterInput>(NULL);
  }

  SpaceFighterInput* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SpaceFighterInput>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SpaceFighterInput& from);
  void MergeFrom(const SpaceFighterInput& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpaceFighterInput* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 actionId = 1;
  void clear_actionid();
  static const int kActionIdFieldNumber = 1;
  ::google::protobuf::int32 actionid() const;
  void set_actionid(::google::protobuf::int32 value);

  // float yaw = 2;
  void clear_yaw();
  static const int kYawFieldNumber = 2;
  float yaw() const;
  void set_yaw(float value);

  // float pitch = 3;
  void clear_pitch();
  static const int kPitchFieldNumber = 3;
  float pitch() const;
  void set_pitch(float value);

  // float rotationSpeed = 4;
  void clear_rotationspeed();
  static const int kRotationSpeedFieldNumber = 4;
  float rotationspeed() const;
  void set_rotationspeed(float value);

  // float rollAngle = 5;
  void clear_rollangle();
  static const int kRollAngleFieldNumber = 5;
  float rollangle() const;
  void set_rollangle(float value);

  // @@protoc_insertion_point(class_scope:multiplayer.SpaceFighterInput)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 actionid_;
  float yaw_;
  float pitch_;
  float rotationspeed_;
  float rollangle_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_space_2dfighter_2fspace_2dfighter_2dinput_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SpaceFighterInput

// int32 actionId = 1;
inline void SpaceFighterInput::clear_actionid() {
  actionid_ = 0;
}
inline ::google::protobuf::int32 SpaceFighterInput::actionid() const {
  // @@protoc_insertion_point(field_get:multiplayer.SpaceFighterInput.actionId)
  return actionid_;
}
inline void SpaceFighterInput::set_actionid(::google::protobuf::int32 value) {
  
  actionid_ = value;
  // @@protoc_insertion_point(field_set:multiplayer.SpaceFighterInput.actionId)
}

// float yaw = 2;
inline void SpaceFighterInput::clear_yaw() {
  yaw_ = 0;
}
inline float SpaceFighterInput::yaw() const {
  // @@protoc_insertion_point(field_get:multiplayer.SpaceFighterInput.yaw)
  return yaw_;
}
inline void SpaceFighterInput::set_yaw(float value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:multiplayer.SpaceFighterInput.yaw)
}

// float pitch = 3;
inline void SpaceFighterInput::clear_pitch() {
  pitch_ = 0;
}
inline float SpaceFighterInput::pitch() const {
  // @@protoc_insertion_point(field_get:multiplayer.SpaceFighterInput.pitch)
  return pitch_;
}
inline void SpaceFighterInput::set_pitch(float value) {
  
  pitch_ = value;
  // @@protoc_insertion_point(field_set:multiplayer.SpaceFighterInput.pitch)
}

// float rotationSpeed = 4;
inline void SpaceFighterInput::clear_rotationspeed() {
  rotationspeed_ = 0;
}
inline float SpaceFighterInput::rotationspeed() const {
  // @@protoc_insertion_point(field_get:multiplayer.SpaceFighterInput.rotationSpeed)
  return rotationspeed_;
}
inline void SpaceFighterInput::set_rotationspeed(float value) {
  
  rotationspeed_ = value;
  // @@protoc_insertion_point(field_set:multiplayer.SpaceFighterInput.rotationSpeed)
}

// float rollAngle = 5;
inline void SpaceFighterInput::clear_rollangle() {
  rollangle_ = 0;
}
inline float SpaceFighterInput::rollangle() const {
  // @@protoc_insertion_point(field_get:multiplayer.SpaceFighterInput.rollAngle)
  return rollangle_;
}
inline void SpaceFighterInput::set_rollangle(float value) {
  
  rollangle_ = value;
  // @@protoc_insertion_point(field_set:multiplayer.SpaceFighterInput.rollAngle)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace multiplayer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_space_2dfighter_2fspace_2dfighter_2dinput_2eproto
