// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: space-fighter/space-fighter-got-hit.proto

#include "space-fighter-got-hit.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace multiplayer {
class SpaceFighterGotHitDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SpaceFighterGotHit>
      _instance;
} _SpaceFighterGotHit_default_instance_;
}  // namespace multiplayer
namespace protobuf_space_2dfighter_2fspace_2dfighter_2dgot_2dhit_2eproto {
static void InitDefaultsSpaceFighterGotHit() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::multiplayer::_SpaceFighterGotHit_default_instance_;
    new (ptr) ::multiplayer::SpaceFighterGotHit();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::multiplayer::SpaceFighterGotHit::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SpaceFighterGotHit =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSpaceFighterGotHit}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SpaceFighterGotHit.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::SpaceFighterGotHit, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::SpaceFighterGotHit, projectileseqid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::SpaceFighterGotHit, projectileindex1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::SpaceFighterGotHit, projectileindex2_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::multiplayer::SpaceFighterGotHit)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::multiplayer::_SpaceFighterGotHit_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "space-fighter/space-fighter-got-hit.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n)space-fighter/space-fighter-got-hit.pr"
      "oto\022\013multiplayer\"a\n\022SpaceFighterGotHit\022\027"
      "\n\017projectileSeqId\030\001 \001(\005\022\030\n\020projectileInd"
      "ex1\030\002 \001(\r\022\030\n\020projectileIndex2\030\003 \001(\rb\006pro"
      "to3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 163);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "space-fighter/space-fighter-got-hit.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_space_2dfighter_2fspace_2dfighter_2dgot_2dhit_2eproto
namespace multiplayer {

// ===================================================================

void SpaceFighterGotHit::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SpaceFighterGotHit::kProjectileSeqIdFieldNumber;
const int SpaceFighterGotHit::kProjectileIndex1FieldNumber;
const int SpaceFighterGotHit::kProjectileIndex2FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SpaceFighterGotHit::SpaceFighterGotHit()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_space_2dfighter_2fspace_2dfighter_2dgot_2dhit_2eproto::scc_info_SpaceFighterGotHit.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:multiplayer.SpaceFighterGotHit)
}
SpaceFighterGotHit::SpaceFighterGotHit(const SpaceFighterGotHit& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&projectileseqid_, &from.projectileseqid_,
    static_cast<size_t>(reinterpret_cast<char*>(&projectileindex2_) -
    reinterpret_cast<char*>(&projectileseqid_)) + sizeof(projectileindex2_));
  // @@protoc_insertion_point(copy_constructor:multiplayer.SpaceFighterGotHit)
}

void SpaceFighterGotHit::SharedCtor() {
  ::memset(&projectileseqid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&projectileindex2_) -
      reinterpret_cast<char*>(&projectileseqid_)) + sizeof(projectileindex2_));
}

SpaceFighterGotHit::~SpaceFighterGotHit() {
  // @@protoc_insertion_point(destructor:multiplayer.SpaceFighterGotHit)
  SharedDtor();
}

void SpaceFighterGotHit::SharedDtor() {
}

void SpaceFighterGotHit::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SpaceFighterGotHit::descriptor() {
  ::protobuf_space_2dfighter_2fspace_2dfighter_2dgot_2dhit_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_space_2dfighter_2fspace_2dfighter_2dgot_2dhit_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SpaceFighterGotHit& SpaceFighterGotHit::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_space_2dfighter_2fspace_2dfighter_2dgot_2dhit_2eproto::scc_info_SpaceFighterGotHit.base);
  return *internal_default_instance();
}


void SpaceFighterGotHit::Clear() {
// @@protoc_insertion_point(message_clear_start:multiplayer.SpaceFighterGotHit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&projectileseqid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&projectileindex2_) -
      reinterpret_cast<char*>(&projectileseqid_)) + sizeof(projectileindex2_));
  _internal_metadata_.Clear();
}

bool SpaceFighterGotHit::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:multiplayer.SpaceFighterGotHit)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 projectileSeqId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &projectileseqid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 projectileIndex1 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &projectileindex1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 projectileIndex2 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &projectileindex2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:multiplayer.SpaceFighterGotHit)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:multiplayer.SpaceFighterGotHit)
  return false;
#undef DO_
}

void SpaceFighterGotHit::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:multiplayer.SpaceFighterGotHit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 projectileSeqId = 1;
  if (this->projectileseqid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->projectileseqid(), output);
  }

  // uint32 projectileIndex1 = 2;
  if (this->projectileindex1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->projectileindex1(), output);
  }

  // uint32 projectileIndex2 = 3;
  if (this->projectileindex2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->projectileindex2(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:multiplayer.SpaceFighterGotHit)
}

::google::protobuf::uint8* SpaceFighterGotHit::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:multiplayer.SpaceFighterGotHit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 projectileSeqId = 1;
  if (this->projectileseqid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->projectileseqid(), target);
  }

  // uint32 projectileIndex1 = 2;
  if (this->projectileindex1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->projectileindex1(), target);
  }

  // uint32 projectileIndex2 = 3;
  if (this->projectileindex2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->projectileindex2(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:multiplayer.SpaceFighterGotHit)
  return target;
}

size_t SpaceFighterGotHit::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:multiplayer.SpaceFighterGotHit)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 projectileSeqId = 1;
  if (this->projectileseqid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->projectileseqid());
  }

  // uint32 projectileIndex1 = 2;
  if (this->projectileindex1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->projectileindex1());
  }

  // uint32 projectileIndex2 = 3;
  if (this->projectileindex2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->projectileindex2());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SpaceFighterGotHit::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:multiplayer.SpaceFighterGotHit)
  GOOGLE_DCHECK_NE(&from, this);
  const SpaceFighterGotHit* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SpaceFighterGotHit>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:multiplayer.SpaceFighterGotHit)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:multiplayer.SpaceFighterGotHit)
    MergeFrom(*source);
  }
}

void SpaceFighterGotHit::MergeFrom(const SpaceFighterGotHit& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:multiplayer.SpaceFighterGotHit)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.projectileseqid() != 0) {
    set_projectileseqid(from.projectileseqid());
  }
  if (from.projectileindex1() != 0) {
    set_projectileindex1(from.projectileindex1());
  }
  if (from.projectileindex2() != 0) {
    set_projectileindex2(from.projectileindex2());
  }
}

void SpaceFighterGotHit::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:multiplayer.SpaceFighterGotHit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpaceFighterGotHit::CopyFrom(const SpaceFighterGotHit& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:multiplayer.SpaceFighterGotHit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpaceFighterGotHit::IsInitialized() const {
  return true;
}

void SpaceFighterGotHit::Swap(SpaceFighterGotHit* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SpaceFighterGotHit::InternalSwap(SpaceFighterGotHit* other) {
  using std::swap;
  swap(projectileseqid_, other->projectileseqid_);
  swap(projectileindex1_, other->projectileindex1_);
  swap(projectileindex2_, other->projectileindex2_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SpaceFighterGotHit::GetMetadata() const {
  protobuf_space_2dfighter_2fspace_2dfighter_2dgot_2dhit_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_space_2dfighter_2fspace_2dfighter_2dgot_2dhit_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace multiplayer
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::multiplayer::SpaceFighterGotHit* Arena::CreateMaybeMessage< ::multiplayer::SpaceFighterGotHit >(Arena* arena) {
  return Arena::CreateInternal< ::multiplayer::SpaceFighterGotHit >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
