// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controls-state.proto

#include "controls-state.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace multiplayer {
class ControlsStateDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ControlsState>
      _instance;
} _ControlsState_default_instance_;
}  // namespace multiplayer
namespace protobuf_controls_2dstate_2eproto {
static void InitDefaultsControlsState() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::multiplayer::_ControlsState_default_instance_;
    new (ptr) ::multiplayer::ControlsState();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::multiplayer::ControlsState::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ControlsState =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsControlsState}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ControlsState.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ControlsState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ControlsState, msgid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ControlsState, yawtarget_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ControlsState, pitchtarget_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ControlsState, rolltarget_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::multiplayer::ControlsState)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::multiplayer::_ControlsState_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "controls-state.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024controls-state.proto\022\013multiplayer\"Z\n\rC"
      "ontrolsState\022\r\n\005msgId\030\001 \001(\005\022\021\n\tyawTarget"
      "\030\002 \001(\002\022\023\n\013pitchTarget\030\003 \001(\002\022\022\n\nrollTarge"
      "t\030\004 \001(\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 135);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "controls-state.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_controls_2dstate_2eproto
namespace multiplayer {

// ===================================================================

void ControlsState::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ControlsState::kMsgIdFieldNumber;
const int ControlsState::kYawTargetFieldNumber;
const int ControlsState::kPitchTargetFieldNumber;
const int ControlsState::kRollTargetFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ControlsState::ControlsState()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_controls_2dstate_2eproto::scc_info_ControlsState.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:multiplayer.ControlsState)
}
ControlsState::ControlsState(const ControlsState& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&msgid_, &from.msgid_,
    static_cast<size_t>(reinterpret_cast<char*>(&rolltarget_) -
    reinterpret_cast<char*>(&msgid_)) + sizeof(rolltarget_));
  // @@protoc_insertion_point(copy_constructor:multiplayer.ControlsState)
}

void ControlsState::SharedCtor() {
  ::memset(&msgid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rolltarget_) -
      reinterpret_cast<char*>(&msgid_)) + sizeof(rolltarget_));
}

ControlsState::~ControlsState() {
  // @@protoc_insertion_point(destructor:multiplayer.ControlsState)
  SharedDtor();
}

void ControlsState::SharedDtor() {
}

void ControlsState::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ControlsState::descriptor() {
  ::protobuf_controls_2dstate_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_controls_2dstate_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ControlsState& ControlsState::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_controls_2dstate_2eproto::scc_info_ControlsState.base);
  return *internal_default_instance();
}


void ControlsState::Clear() {
// @@protoc_insertion_point(message_clear_start:multiplayer.ControlsState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&msgid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rolltarget_) -
      reinterpret_cast<char*>(&msgid_)) + sizeof(rolltarget_));
  _internal_metadata_.Clear();
}

bool ControlsState::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:multiplayer.ControlsState)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 msgId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &msgid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float yawTarget = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &yawtarget_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float pitchTarget = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pitchtarget_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float rollTarget = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &rolltarget_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:multiplayer.ControlsState)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:multiplayer.ControlsState)
  return false;
#undef DO_
}

void ControlsState::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:multiplayer.ControlsState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 msgId = 1;
  if (this->msgid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->msgid(), output);
  }

  // float yawTarget = 2;
  if (this->yawtarget() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->yawtarget(), output);
  }

  // float pitchTarget = 3;
  if (this->pitchtarget() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->pitchtarget(), output);
  }

  // float rollTarget = 4;
  if (this->rolltarget() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->rolltarget(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:multiplayer.ControlsState)
}

::google::protobuf::uint8* ControlsState::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:multiplayer.ControlsState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 msgId = 1;
  if (this->msgid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->msgid(), target);
  }

  // float yawTarget = 2;
  if (this->yawtarget() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->yawtarget(), target);
  }

  // float pitchTarget = 3;
  if (this->pitchtarget() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->pitchtarget(), target);
  }

  // float rollTarget = 4;
  if (this->rolltarget() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->rolltarget(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:multiplayer.ControlsState)
  return target;
}

size_t ControlsState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:multiplayer.ControlsState)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 msgId = 1;
  if (this->msgid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->msgid());
  }

  // float yawTarget = 2;
  if (this->yawtarget() != 0) {
    total_size += 1 + 4;
  }

  // float pitchTarget = 3;
  if (this->pitchtarget() != 0) {
    total_size += 1 + 4;
  }

  // float rollTarget = 4;
  if (this->rolltarget() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ControlsState::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:multiplayer.ControlsState)
  GOOGLE_DCHECK_NE(&from, this);
  const ControlsState* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ControlsState>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:multiplayer.ControlsState)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:multiplayer.ControlsState)
    MergeFrom(*source);
  }
}

void ControlsState::MergeFrom(const ControlsState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:multiplayer.ControlsState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.msgid() != 0) {
    set_msgid(from.msgid());
  }
  if (from.yawtarget() != 0) {
    set_yawtarget(from.yawtarget());
  }
  if (from.pitchtarget() != 0) {
    set_pitchtarget(from.pitchtarget());
  }
  if (from.rolltarget() != 0) {
    set_rolltarget(from.rolltarget());
  }
}

void ControlsState::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:multiplayer.ControlsState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ControlsState::CopyFrom(const ControlsState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:multiplayer.ControlsState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ControlsState::IsInitialized() const {
  return true;
}

void ControlsState::Swap(ControlsState* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ControlsState::InternalSwap(ControlsState* other) {
  using std::swap;
  swap(msgid_, other->msgid_);
  swap(yawtarget_, other->yawtarget_);
  swap(pitchtarget_, other->pitchtarget_);
  swap(rolltarget_, other->rolltarget_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ControlsState::GetMetadata() const {
  protobuf_controls_2dstate_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_controls_2dstate_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace multiplayer
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::multiplayer::ControlsState* Arena::CreateMaybeMessage< ::multiplayer::ControlsState >(Arena* arena) {
  return Arena::CreateInternal< ::multiplayer::ControlsState >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
