// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object-state.proto

#include "object-state.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_space_2dfighter_2fspace_2dfighter_2dstate_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_space_2dfighter_2fspace_2dfighter_2dstate_2eproto ::google::protobuf::internal::SCCInfo<3> scc_info_SpaceFighterState;
}  // namespace protobuf_space_2dfighter_2fspace_2dfighter_2dstate_2eproto
namespace multiplayer {
class ObjectStateDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ObjectState>
      _instance;
  const ::multiplayer::SpaceFighterState* spacefighterstate_;
} _ObjectState_default_instance_;
}  // namespace multiplayer
namespace protobuf_object_2dstate_2eproto {
static void InitDefaultsObjectState() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::multiplayer::_ObjectState_default_instance_;
    new (ptr) ::multiplayer::ObjectState();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::multiplayer::ObjectState::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ObjectState =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsObjectState}, {
      &protobuf_space_2dfighter_2fspace_2dfighter_2dstate_2eproto::scc_info_SpaceFighterState.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ObjectState.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ObjectState, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ObjectState, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ObjectState, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ObjectState, objecttype_),
  offsetof(::multiplayer::ObjectStateDefaultTypeInternal, spacefighterstate_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ObjectState, state_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::multiplayer::ObjectState)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::multiplayer::_ObjectState_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "object-state.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022object-state.proto\022\013multiplayer\032\'space"
      "-fighter/space-fighter-state.proto\"s\n\013Ob"
      "jectState\022\n\n\002id\030\001 \001(\005\022\022\n\nobjectType\030\002 \001("
      "\005\022;\n\021spaceFighterState\030\003 \001(\0132\036.multiplay"
      "er.SpaceFighterStateH\000B\007\n\005stateb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 199);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "object-state.proto", &protobuf_RegisterTypes);
  ::protobuf_space_2dfighter_2fspace_2dfighter_2dstate_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_object_2dstate_2eproto
namespace multiplayer {

// ===================================================================

void ObjectState::InitAsDefaultInstance() {
  ::multiplayer::_ObjectState_default_instance_.spacefighterstate_ = const_cast< ::multiplayer::SpaceFighterState*>(
      ::multiplayer::SpaceFighterState::internal_default_instance());
}
void ObjectState::set_allocated_spacefighterstate(::multiplayer::SpaceFighterState* spacefighterstate) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_state();
  if (spacefighterstate) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      spacefighterstate = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, spacefighterstate, submessage_arena);
    }
    set_has_spacefighterstate();
    state_.spacefighterstate_ = spacefighterstate;
  }
  // @@protoc_insertion_point(field_set_allocated:multiplayer.ObjectState.spaceFighterState)
}
void ObjectState::clear_spacefighterstate() {
  if (has_spacefighterstate()) {
    delete state_.spacefighterstate_;
    clear_has_state();
  }
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ObjectState::kIdFieldNumber;
const int ObjectState::kObjectTypeFieldNumber;
const int ObjectState::kSpaceFighterStateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ObjectState::ObjectState()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_object_2dstate_2eproto::scc_info_ObjectState.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:multiplayer.ObjectState)
}
ObjectState::ObjectState(const ObjectState& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&objecttype_) -
    reinterpret_cast<char*>(&id_)) + sizeof(objecttype_));
  clear_has_state();
  switch (from.state_case()) {
    case kSpaceFighterState: {
      mutable_spacefighterstate()->::multiplayer::SpaceFighterState::MergeFrom(from.spacefighterstate());
      break;
    }
    case STATE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:multiplayer.ObjectState)
}

void ObjectState::SharedCtor() {
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&objecttype_) -
      reinterpret_cast<char*>(&id_)) + sizeof(objecttype_));
  clear_has_state();
}

ObjectState::~ObjectState() {
  // @@protoc_insertion_point(destructor:multiplayer.ObjectState)
  SharedDtor();
}

void ObjectState::SharedDtor() {
  if (has_state()) {
    clear_state();
  }
}

void ObjectState::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ObjectState::descriptor() {
  ::protobuf_object_2dstate_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_object_2dstate_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ObjectState& ObjectState::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_object_2dstate_2eproto::scc_info_ObjectState.base);
  return *internal_default_instance();
}


void ObjectState::clear_state() {
// @@protoc_insertion_point(one_of_clear_start:multiplayer.ObjectState)
  switch (state_case()) {
    case kSpaceFighterState: {
      delete state_.spacefighterstate_;
      break;
    }
    case STATE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = STATE_NOT_SET;
}


void ObjectState::Clear() {
// @@protoc_insertion_point(message_clear_start:multiplayer.ObjectState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&objecttype_) -
      reinterpret_cast<char*>(&id_)) + sizeof(objecttype_));
  clear_state();
  _internal_metadata_.Clear();
}

bool ObjectState::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:multiplayer.ObjectState)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 objectType = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &objecttype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .multiplayer.SpaceFighterState spaceFighterState = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_spacefighterstate()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:multiplayer.ObjectState)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:multiplayer.ObjectState)
  return false;
#undef DO_
}

void ObjectState::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:multiplayer.ObjectState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // int32 objectType = 2;
  if (this->objecttype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->objecttype(), output);
  }

  // .multiplayer.SpaceFighterState spaceFighterState = 3;
  if (has_spacefighterstate()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_spacefighterstate(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:multiplayer.ObjectState)
}

::google::protobuf::uint8* ObjectState::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:multiplayer.ObjectState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // int32 objectType = 2;
  if (this->objecttype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->objecttype(), target);
  }

  // .multiplayer.SpaceFighterState spaceFighterState = 3;
  if (has_spacefighterstate()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_spacefighterstate(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:multiplayer.ObjectState)
  return target;
}

size_t ObjectState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:multiplayer.ObjectState)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  // int32 objectType = 2;
  if (this->objecttype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->objecttype());
  }

  switch (state_case()) {
    // .multiplayer.SpaceFighterState spaceFighterState = 3;
    case kSpaceFighterState: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *state_.spacefighterstate_);
      break;
    }
    case STATE_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ObjectState::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:multiplayer.ObjectState)
  GOOGLE_DCHECK_NE(&from, this);
  const ObjectState* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ObjectState>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:multiplayer.ObjectState)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:multiplayer.ObjectState)
    MergeFrom(*source);
  }
}

void ObjectState::MergeFrom(const ObjectState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:multiplayer.ObjectState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.objecttype() != 0) {
    set_objecttype(from.objecttype());
  }
  switch (from.state_case()) {
    case kSpaceFighterState: {
      mutable_spacefighterstate()->::multiplayer::SpaceFighterState::MergeFrom(from.spacefighterstate());
      break;
    }
    case STATE_NOT_SET: {
      break;
    }
  }
}

void ObjectState::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:multiplayer.ObjectState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObjectState::CopyFrom(const ObjectState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:multiplayer.ObjectState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObjectState::IsInitialized() const {
  return true;
}

void ObjectState::Swap(ObjectState* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ObjectState::InternalSwap(ObjectState* other) {
  using std::swap;
  swap(id_, other->id_);
  swap(objecttype_, other->objecttype_);
  swap(state_, other->state_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ObjectState::GetMetadata() const {
  protobuf_object_2dstate_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_object_2dstate_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace multiplayer
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::multiplayer::ObjectState* Arena::CreateMaybeMessage< ::multiplayer::ObjectState >(Arena* arena) {
  return Arena::CreateInternal< ::multiplayer::ObjectState >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
