// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: quaternion.proto

#ifndef PROTOBUF_INCLUDED_quaternion_2eproto
#define PROTOBUF_INCLUDED_quaternion_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "float-vector.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_quaternion_2eproto 

namespace protobuf_quaternion_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_quaternion_2eproto
namespace multiplayer {
class Quaternion;
class QuaternionDefaultTypeInternal;
extern QuaternionDefaultTypeInternal _Quaternion_default_instance_;
}  // namespace multiplayer
namespace google {
namespace protobuf {
template<> ::multiplayer::Quaternion* Arena::CreateMaybeMessage<::multiplayer::Quaternion>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace multiplayer {

// ===================================================================

class Quaternion : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:multiplayer.Quaternion) */ {
 public:
  Quaternion();
  virtual ~Quaternion();

  Quaternion(const Quaternion& from);

  inline Quaternion& operator=(const Quaternion& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Quaternion(Quaternion&& from) noexcept
    : Quaternion() {
    *this = ::std::move(from);
  }

  inline Quaternion& operator=(Quaternion&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Quaternion& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Quaternion* internal_default_instance() {
    return reinterpret_cast<const Quaternion*>(
               &_Quaternion_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Quaternion* other);
  friend void swap(Quaternion& a, Quaternion& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Quaternion* New() const final {
    return CreateMaybeMessage<Quaternion>(NULL);
  }

  Quaternion* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Quaternion>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Quaternion& from);
  void MergeFrom(const Quaternion& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Quaternion* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .multiplayer.FloatVector imag = 1;
  bool has_imag() const;
  void clear_imag();
  static const int kImagFieldNumber = 1;
  private:
  const ::multiplayer::FloatVector& _internal_imag() const;
  public:
  const ::multiplayer::FloatVector& imag() const;
  ::multiplayer::FloatVector* release_imag();
  ::multiplayer::FloatVector* mutable_imag();
  void set_allocated_imag(::multiplayer::FloatVector* imag);

  // float real = 2;
  void clear_real();
  static const int kRealFieldNumber = 2;
  float real() const;
  void set_real(float value);

  // @@protoc_insertion_point(class_scope:multiplayer.Quaternion)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::multiplayer::FloatVector* imag_;
  float real_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_quaternion_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Quaternion

// .multiplayer.FloatVector imag = 1;
inline bool Quaternion::has_imag() const {
  return this != internal_default_instance() && imag_ != NULL;
}
inline const ::multiplayer::FloatVector& Quaternion::_internal_imag() const {
  return *imag_;
}
inline const ::multiplayer::FloatVector& Quaternion::imag() const {
  const ::multiplayer::FloatVector* p = imag_;
  // @@protoc_insertion_point(field_get:multiplayer.Quaternion.imag)
  return p != NULL ? *p : *reinterpret_cast<const ::multiplayer::FloatVector*>(
      &::multiplayer::_FloatVector_default_instance_);
}
inline ::multiplayer::FloatVector* Quaternion::release_imag() {
  // @@protoc_insertion_point(field_release:multiplayer.Quaternion.imag)
  
  ::multiplayer::FloatVector* temp = imag_;
  imag_ = NULL;
  return temp;
}
inline ::multiplayer::FloatVector* Quaternion::mutable_imag() {
  
  if (imag_ == NULL) {
    auto* p = CreateMaybeMessage<::multiplayer::FloatVector>(GetArenaNoVirtual());
    imag_ = p;
  }
  // @@protoc_insertion_point(field_mutable:multiplayer.Quaternion.imag)
  return imag_;
}
inline void Quaternion::set_allocated_imag(::multiplayer::FloatVector* imag) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(imag_);
  }
  if (imag) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      imag = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, imag, submessage_arena);
    }
    
  } else {
    
  }
  imag_ = imag;
  // @@protoc_insertion_point(field_set_allocated:multiplayer.Quaternion.imag)
}

// float real = 2;
inline void Quaternion::clear_real() {
  real_ = 0;
}
inline float Quaternion::real() const {
  // @@protoc_insertion_point(field_get:multiplayer.Quaternion.real)
  return real_;
}
inline void Quaternion::set_real(float value) {
  
  real_ = value;
  // @@protoc_insertion_point(field_set:multiplayer.Quaternion.real)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace multiplayer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_quaternion_2eproto
