// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request-ack.proto

#ifndef PROTOBUF_INCLUDED_request_2dack_2eproto
#define PROTOBUF_INCLUDED_request_2dack_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_request_2dack_2eproto 

namespace protobuf_request_2dack_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_request_2dack_2eproto
namespace multiplayer {
class RequestAck;
class RequestAckDefaultTypeInternal;
extern RequestAckDefaultTypeInternal _RequestAck_default_instance_;
}  // namespace multiplayer
namespace google {
namespace protobuf {
template<> ::multiplayer::RequestAck* Arena::CreateMaybeMessage<::multiplayer::RequestAck>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace multiplayer {

// ===================================================================

class RequestAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:multiplayer.RequestAck) */ {
 public:
  RequestAck();
  virtual ~RequestAck();

  RequestAck(const RequestAck& from);

  inline RequestAck& operator=(const RequestAck& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RequestAck(RequestAck&& from) noexcept
    : RequestAck() {
    *this = ::std::move(from);
  }

  inline RequestAck& operator=(RequestAck&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestAck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RequestAck* internal_default_instance() {
    return reinterpret_cast<const RequestAck*>(
               &_RequestAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(RequestAck* other);
  friend void swap(RequestAck& a, RequestAck& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RequestAck* New() const final {
    return CreateMaybeMessage<RequestAck>(NULL);
  }

  RequestAck* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RequestAck>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RequestAck& from);
  void MergeFrom(const RequestAck& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 requestSentTimestamp = 2;
  void clear_requestsenttimestamp();
  static const int kRequestSentTimestampFieldNumber = 2;
  ::google::protobuf::uint64 requestsenttimestamp() const;
  void set_requestsenttimestamp(::google::protobuf::uint64 value);

  // int32 requestId = 1;
  void clear_requestid();
  static const int kRequestIdFieldNumber = 1;
  ::google::protobuf::int32 requestid() const;
  void set_requestid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:multiplayer.RequestAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 requestsenttimestamp_;
  ::google::protobuf::int32 requestid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_request_2dack_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RequestAck

// int32 requestId = 1;
inline void RequestAck::clear_requestid() {
  requestid_ = 0;
}
inline ::google::protobuf::int32 RequestAck::requestid() const {
  // @@protoc_insertion_point(field_get:multiplayer.RequestAck.requestId)
  return requestid_;
}
inline void RequestAck::set_requestid(::google::protobuf::int32 value) {
  
  requestid_ = value;
  // @@protoc_insertion_point(field_set:multiplayer.RequestAck.requestId)
}

// uint64 requestSentTimestamp = 2;
inline void RequestAck::clear_requestsenttimestamp() {
  requestsenttimestamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 RequestAck::requestsenttimestamp() const {
  // @@protoc_insertion_point(field_get:multiplayer.RequestAck.requestSentTimestamp)
  return requestsenttimestamp_;
}
inline void RequestAck::set_requestsenttimestamp(::google::protobuf::uint64 value) {
  
  requestsenttimestamp_ = value;
  // @@protoc_insertion_point(field_set:multiplayer.RequestAck.requestSentTimestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace multiplayer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_request_2dack_2eproto
