// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response-root.proto

#ifndef PROTOBUF_INCLUDED_response_2droot_2eproto
#define PROTOBUF_INCLUDED_response_2droot_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "world-state.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_response_2droot_2eproto 

namespace protobuf_response_2droot_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_response_2droot_2eproto
namespace multiplayer {
class ResponseRoot;
class ResponseRootDefaultTypeInternal;
extern ResponseRootDefaultTypeInternal _ResponseRoot_default_instance_;
}  // namespace multiplayer
namespace google {
namespace protobuf {
template<> ::multiplayer::ResponseRoot* Arena::CreateMaybeMessage<::multiplayer::ResponseRoot>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace multiplayer {

// ===================================================================

class ResponseRoot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:multiplayer.ResponseRoot) */ {
 public:
  ResponseRoot();
  virtual ~ResponseRoot();

  ResponseRoot(const ResponseRoot& from);

  inline ResponseRoot& operator=(const ResponseRoot& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResponseRoot(ResponseRoot&& from) noexcept
    : ResponseRoot() {
    *this = ::std::move(from);
  }

  inline ResponseRoot& operator=(ResponseRoot&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseRoot& default_instance();

  enum MessageCase {
    kWorldState = 1,
    MESSAGE_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResponseRoot* internal_default_instance() {
    return reinterpret_cast<const ResponseRoot*>(
               &_ResponseRoot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ResponseRoot* other);
  friend void swap(ResponseRoot& a, ResponseRoot& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResponseRoot* New() const final {
    return CreateMaybeMessage<ResponseRoot>(NULL);
  }

  ResponseRoot* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResponseRoot>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResponseRoot& from);
  void MergeFrom(const ResponseRoot& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResponseRoot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .multiplayer.WorldState worldState = 1;
  bool has_worldstate() const;
  void clear_worldstate();
  static const int kWorldStateFieldNumber = 1;
  private:
  const ::multiplayer::WorldState& _internal_worldstate() const;
  public:
  const ::multiplayer::WorldState& worldstate() const;
  ::multiplayer::WorldState* release_worldstate();
  ::multiplayer::WorldState* mutable_worldstate();
  void set_allocated_worldstate(::multiplayer::WorldState* worldstate);

  void clear_message();
  MessageCase message_case() const;
  // @@protoc_insertion_point(class_scope:multiplayer.ResponseRoot)
 private:
  void set_has_worldstate();

  inline bool has_message() const;
  inline void clear_has_message();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  union MessageUnion {
    MessageUnion() {}
    ::multiplayer::WorldState* worldstate_;
  } message_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::protobuf_response_2droot_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResponseRoot

// .multiplayer.WorldState worldState = 1;
inline bool ResponseRoot::has_worldstate() const {
  return message_case() == kWorldState;
}
inline void ResponseRoot::set_has_worldstate() {
  _oneof_case_[0] = kWorldState;
}
inline const ::multiplayer::WorldState& ResponseRoot::_internal_worldstate() const {
  return *message_.worldstate_;
}
inline ::multiplayer::WorldState* ResponseRoot::release_worldstate() {
  // @@protoc_insertion_point(field_release:multiplayer.ResponseRoot.worldState)
  if (has_worldstate()) {
    clear_has_message();
      ::multiplayer::WorldState* temp = message_.worldstate_;
    message_.worldstate_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::multiplayer::WorldState& ResponseRoot::worldstate() const {
  // @@protoc_insertion_point(field_get:multiplayer.ResponseRoot.worldState)
  return has_worldstate()
      ? *message_.worldstate_
      : *reinterpret_cast< ::multiplayer::WorldState*>(&::multiplayer::_WorldState_default_instance_);
}
inline ::multiplayer::WorldState* ResponseRoot::mutable_worldstate() {
  if (!has_worldstate()) {
    clear_message();
    set_has_worldstate();
    message_.worldstate_ = CreateMaybeMessage< ::multiplayer::WorldState >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:multiplayer.ResponseRoot.worldState)
  return message_.worldstate_;
}

inline bool ResponseRoot::has_message() const {
  return message_case() != MESSAGE_NOT_SET;
}
inline void ResponseRoot::clear_has_message() {
  _oneof_case_[0] = MESSAGE_NOT_SET;
}
inline ResponseRoot::MessageCase ResponseRoot::message_case() const {
  return ResponseRoot::MessageCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace multiplayer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_response_2droot_2eproto
