// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response-root.proto

#include "response-root.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_spawn_2dresponse_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_spawn_2dresponse_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_SpawnResponse;
}  // namespace protobuf_spawn_2dresponse_2eproto
namespace protobuf_world_2dstate_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_world_2dstate_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_WorldState;
}  // namespace protobuf_world_2dstate_2eproto
namespace multiplayer {
class ResponseRootDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ResponseRoot>
      _instance;
  const ::multiplayer::WorldState* worldstate_;
  const ::multiplayer::SpawnResponse* spawnresponse_;
} _ResponseRoot_default_instance_;
}  // namespace multiplayer
namespace protobuf_response_2droot_2eproto {
static void InitDefaultsResponseRoot() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::multiplayer::_ResponseRoot_default_instance_;
    new (ptr) ::multiplayer::ResponseRoot();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::multiplayer::ResponseRoot::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_ResponseRoot =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsResponseRoot}, {
      &protobuf_world_2dstate_2eproto::scc_info_WorldState.base,
      &protobuf_spawn_2dresponse_2eproto::scc_info_SpawnResponse.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ResponseRoot.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ResponseRoot, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ResponseRoot, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ResponseRoot, requestid_),
  offsetof(::multiplayer::ResponseRootDefaultTypeInternal, worldstate_),
  offsetof(::multiplayer::ResponseRootDefaultTypeInternal, spawnresponse_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::ResponseRoot, message_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::multiplayer::ResponseRoot)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::multiplayer::_ResponseRoot_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "response-root.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023response-root.proto\022\013multiplayer\032\021worl"
      "d-state.proto\032\024spawn-response.proto\"\220\001\n\014"
      "ResponseRoot\022\021\n\trequestId\030\001 \001(\005\022-\n\nworld"
      "State\030\002 \001(\0132\027.multiplayer.WorldStateH\000\0223"
      "\n\rspawnResponse\030\003 \001(\0132\032.multiplayer.Spaw"
      "nResponseH\000B\t\n\007messageb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 230);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "response-root.proto", &protobuf_RegisterTypes);
  ::protobuf_world_2dstate_2eproto::AddDescriptors();
  ::protobuf_spawn_2dresponse_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_response_2droot_2eproto
namespace multiplayer {

// ===================================================================

void ResponseRoot::InitAsDefaultInstance() {
  ::multiplayer::_ResponseRoot_default_instance_.worldstate_ = const_cast< ::multiplayer::WorldState*>(
      ::multiplayer::WorldState::internal_default_instance());
  ::multiplayer::_ResponseRoot_default_instance_.spawnresponse_ = const_cast< ::multiplayer::SpawnResponse*>(
      ::multiplayer::SpawnResponse::internal_default_instance());
}
void ResponseRoot::set_allocated_worldstate(::multiplayer::WorldState* worldstate) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_message();
  if (worldstate) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      worldstate = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, worldstate, submessage_arena);
    }
    set_has_worldstate();
    message_.worldstate_ = worldstate;
  }
  // @@protoc_insertion_point(field_set_allocated:multiplayer.ResponseRoot.worldState)
}
void ResponseRoot::clear_worldstate() {
  if (has_worldstate()) {
    delete message_.worldstate_;
    clear_has_message();
  }
}
void ResponseRoot::set_allocated_spawnresponse(::multiplayer::SpawnResponse* spawnresponse) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_message();
  if (spawnresponse) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      spawnresponse = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, spawnresponse, submessage_arena);
    }
    set_has_spawnresponse();
    message_.spawnresponse_ = spawnresponse;
  }
  // @@protoc_insertion_point(field_set_allocated:multiplayer.ResponseRoot.spawnResponse)
}
void ResponseRoot::clear_spawnresponse() {
  if (has_spawnresponse()) {
    delete message_.spawnresponse_;
    clear_has_message();
  }
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResponseRoot::kRequestIdFieldNumber;
const int ResponseRoot::kWorldStateFieldNumber;
const int ResponseRoot::kSpawnResponseFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ResponseRoot::ResponseRoot()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_response_2droot_2eproto::scc_info_ResponseRoot.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:multiplayer.ResponseRoot)
}
ResponseRoot::ResponseRoot(const ResponseRoot& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  requestid_ = from.requestid_;
  clear_has_message();
  switch (from.message_case()) {
    case kWorldState: {
      mutable_worldstate()->::multiplayer::WorldState::MergeFrom(from.worldstate());
      break;
    }
    case kSpawnResponse: {
      mutable_spawnresponse()->::multiplayer::SpawnResponse::MergeFrom(from.spawnresponse());
      break;
    }
    case MESSAGE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:multiplayer.ResponseRoot)
}

void ResponseRoot::SharedCtor() {
  requestid_ = 0;
  clear_has_message();
}

ResponseRoot::~ResponseRoot() {
  // @@protoc_insertion_point(destructor:multiplayer.ResponseRoot)
  SharedDtor();
}

void ResponseRoot::SharedDtor() {
  if (has_message()) {
    clear_message();
  }
}

void ResponseRoot::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ResponseRoot::descriptor() {
  ::protobuf_response_2droot_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_response_2droot_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ResponseRoot& ResponseRoot::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_response_2droot_2eproto::scc_info_ResponseRoot.base);
  return *internal_default_instance();
}


void ResponseRoot::clear_message() {
// @@protoc_insertion_point(one_of_clear_start:multiplayer.ResponseRoot)
  switch (message_case()) {
    case kWorldState: {
      delete message_.worldstate_;
      break;
    }
    case kSpawnResponse: {
      delete message_.spawnresponse_;
      break;
    }
    case MESSAGE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = MESSAGE_NOT_SET;
}


void ResponseRoot::Clear() {
// @@protoc_insertion_point(message_clear_start:multiplayer.ResponseRoot)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  requestid_ = 0;
  clear_message();
  _internal_metadata_.Clear();
}

bool ResponseRoot::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:multiplayer.ResponseRoot)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 requestId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &requestid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .multiplayer.WorldState worldState = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_worldstate()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .multiplayer.SpawnResponse spawnResponse = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_spawnresponse()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:multiplayer.ResponseRoot)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:multiplayer.ResponseRoot)
  return false;
#undef DO_
}

void ResponseRoot::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:multiplayer.ResponseRoot)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 requestId = 1;
  if (this->requestid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->requestid(), output);
  }

  // .multiplayer.WorldState worldState = 2;
  if (has_worldstate()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_worldstate(), output);
  }

  // .multiplayer.SpawnResponse spawnResponse = 3;
  if (has_spawnresponse()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_spawnresponse(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:multiplayer.ResponseRoot)
}

::google::protobuf::uint8* ResponseRoot::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:multiplayer.ResponseRoot)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 requestId = 1;
  if (this->requestid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->requestid(), target);
  }

  // .multiplayer.WorldState worldState = 2;
  if (has_worldstate()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_worldstate(), deterministic, target);
  }

  // .multiplayer.SpawnResponse spawnResponse = 3;
  if (has_spawnresponse()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_spawnresponse(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:multiplayer.ResponseRoot)
  return target;
}

size_t ResponseRoot::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:multiplayer.ResponseRoot)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 requestId = 1;
  if (this->requestid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->requestid());
  }

  switch (message_case()) {
    // .multiplayer.WorldState worldState = 2;
    case kWorldState: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *message_.worldstate_);
      break;
    }
    // .multiplayer.SpawnResponse spawnResponse = 3;
    case kSpawnResponse: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *message_.spawnresponse_);
      break;
    }
    case MESSAGE_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResponseRoot::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:multiplayer.ResponseRoot)
  GOOGLE_DCHECK_NE(&from, this);
  const ResponseRoot* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ResponseRoot>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:multiplayer.ResponseRoot)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:multiplayer.ResponseRoot)
    MergeFrom(*source);
  }
}

void ResponseRoot::MergeFrom(const ResponseRoot& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:multiplayer.ResponseRoot)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.requestid() != 0) {
    set_requestid(from.requestid());
  }
  switch (from.message_case()) {
    case kWorldState: {
      mutable_worldstate()->::multiplayer::WorldState::MergeFrom(from.worldstate());
      break;
    }
    case kSpawnResponse: {
      mutable_spawnresponse()->::multiplayer::SpawnResponse::MergeFrom(from.spawnresponse());
      break;
    }
    case MESSAGE_NOT_SET: {
      break;
    }
  }
}

void ResponseRoot::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:multiplayer.ResponseRoot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResponseRoot::CopyFrom(const ResponseRoot& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:multiplayer.ResponseRoot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResponseRoot::IsInitialized() const {
  return true;
}

void ResponseRoot::Swap(ResponseRoot* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ResponseRoot::InternalSwap(ResponseRoot* other) {
  using std::swap;
  swap(requestid_, other->requestid_);
  swap(message_, other->message_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ResponseRoot::GetMetadata() const {
  protobuf_response_2droot_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_response_2droot_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace multiplayer
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::multiplayer::ResponseRoot* Arena::CreateMaybeMessage< ::multiplayer::ResponseRoot >(Arena* arena) {
  return Arena::CreateInternal< ::multiplayer::ResponseRoot >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
