// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spawn-response.proto

#include "spawn-response.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace multiplayer {
class SpawnResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SpawnResponse>
      _instance;
} _SpawnResponse_default_instance_;
}  // namespace multiplayer
namespace protobuf_spawn_2dresponse_2eproto {
static void InitDefaultsSpawnResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::multiplayer::_SpawnResponse_default_instance_;
    new (ptr) ::multiplayer::SpawnResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::multiplayer::SpawnResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SpawnResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSpawnResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SpawnResponse.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::SpawnResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::SpawnResponse, assignedobjectid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::multiplayer::SpawnResponse, spawnrequestid_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::multiplayer::SpawnResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::multiplayer::_SpawnResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "spawn-response.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024spawn-response.proto\022\013multiplayer\"A\n\rS"
      "pawnResponse\022\030\n\020assignedObjectId\030\001 \001(\005\022\026"
      "\n\016spawnRequestId\030\002 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 110);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "spawn-response.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_spawn_2dresponse_2eproto
namespace multiplayer {

// ===================================================================

void SpawnResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SpawnResponse::kAssignedObjectIdFieldNumber;
const int SpawnResponse::kSpawnRequestIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SpawnResponse::SpawnResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_spawn_2dresponse_2eproto::scc_info_SpawnResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:multiplayer.SpawnResponse)
}
SpawnResponse::SpawnResponse(const SpawnResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  spawnrequestid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.spawnrequestid().size() > 0) {
    spawnrequestid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.spawnrequestid_);
  }
  assignedobjectid_ = from.assignedobjectid_;
  // @@protoc_insertion_point(copy_constructor:multiplayer.SpawnResponse)
}

void SpawnResponse::SharedCtor() {
  spawnrequestid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  assignedobjectid_ = 0;
}

SpawnResponse::~SpawnResponse() {
  // @@protoc_insertion_point(destructor:multiplayer.SpawnResponse)
  SharedDtor();
}

void SpawnResponse::SharedDtor() {
  spawnrequestid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SpawnResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SpawnResponse::descriptor() {
  ::protobuf_spawn_2dresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_spawn_2dresponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SpawnResponse& SpawnResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_spawn_2dresponse_2eproto::scc_info_SpawnResponse.base);
  return *internal_default_instance();
}


void SpawnResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:multiplayer.SpawnResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  spawnrequestid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  assignedobjectid_ = 0;
  _internal_metadata_.Clear();
}

bool SpawnResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:multiplayer.SpawnResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 assignedObjectId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &assignedobjectid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string spawnRequestId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_spawnrequestid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->spawnrequestid().data(), static_cast<int>(this->spawnrequestid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "multiplayer.SpawnResponse.spawnRequestId"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:multiplayer.SpawnResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:multiplayer.SpawnResponse)
  return false;
#undef DO_
}

void SpawnResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:multiplayer.SpawnResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 assignedObjectId = 1;
  if (this->assignedobjectid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->assignedobjectid(), output);
  }

  // string spawnRequestId = 2;
  if (this->spawnrequestid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->spawnrequestid().data(), static_cast<int>(this->spawnrequestid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "multiplayer.SpawnResponse.spawnRequestId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->spawnrequestid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:multiplayer.SpawnResponse)
}

::google::protobuf::uint8* SpawnResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:multiplayer.SpawnResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 assignedObjectId = 1;
  if (this->assignedobjectid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->assignedobjectid(), target);
  }

  // string spawnRequestId = 2;
  if (this->spawnrequestid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->spawnrequestid().data(), static_cast<int>(this->spawnrequestid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "multiplayer.SpawnResponse.spawnRequestId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->spawnrequestid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:multiplayer.SpawnResponse)
  return target;
}

size_t SpawnResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:multiplayer.SpawnResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string spawnRequestId = 2;
  if (this->spawnrequestid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->spawnrequestid());
  }

  // int32 assignedObjectId = 1;
  if (this->assignedobjectid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->assignedobjectid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SpawnResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:multiplayer.SpawnResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const SpawnResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SpawnResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:multiplayer.SpawnResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:multiplayer.SpawnResponse)
    MergeFrom(*source);
  }
}

void SpawnResponse::MergeFrom(const SpawnResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:multiplayer.SpawnResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.spawnrequestid().size() > 0) {

    spawnrequestid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.spawnrequestid_);
  }
  if (from.assignedobjectid() != 0) {
    set_assignedobjectid(from.assignedobjectid());
  }
}

void SpawnResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:multiplayer.SpawnResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpawnResponse::CopyFrom(const SpawnResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:multiplayer.SpawnResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpawnResponse::IsInitialized() const {
  return true;
}

void SpawnResponse::Swap(SpawnResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SpawnResponse::InternalSwap(SpawnResponse* other) {
  using std::swap;
  spawnrequestid_.Swap(&other->spawnrequestid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(assignedobjectid_, other->assignedobjectid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SpawnResponse::GetMetadata() const {
  protobuf_spawn_2dresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_spawn_2dresponse_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace multiplayer
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::multiplayer::SpawnResponse* Arena::CreateMaybeMessage< ::multiplayer::SpawnResponse >(Arena* arena) {
  return Arena::CreateInternal< ::multiplayer::SpawnResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
